[package]
name = "ginc"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
ast = { workspace = true }
interface = { workspace = true }
diagnostic = { workspace = true }
typecheck = { workspace = true }
codegen = { workspace = true }
resolve = { workspace = true }
analysis = { workspace = true }
parser = { workspace = true }
flask = { workspace = true }
clap = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = "0.5"
test-fixtures = { workspace = true }

# [[bench]]
# name = "lexer_bench"
# harness = false
