id = "gin"
name = "Gin"
version = "0.1.0"
schema_version = 1
authors = ["Patrick Trickett"]
description = "Language support for the Gin programming language"
repository = "https://github.com/patrickett/gin"

[grammars.gin]
repository = "https://github.com/patrickett/gin"
rev = "d02d73e2c5ea742495d26359779867fe6080a9a1"
path = "editors/tree-sitter-gin"

[language_servers.ginlsp]
name = "Gin Language Server"
languages = ["Gin", "JSON"]
