id = "gin"
name = "Gin"
version = "0.1.0"
schema_version = 1
authors = ["Patrick Trickett"]
description = "Language support for the Gin programming language"
repository = "https://github.com/patrickett/gin"

[grammars.gin]
repository = "https://github.com/patrickett/gin"
rev = "8235ea3448064f9b00d6e1053588912d62460c73"
path = "editors/tree-sitter-gin"

[language_servers.ginlsp]
name = "Gin Language Server"
languages = ["Gin", "JSON"]
