id = "gin"
name = "Gin"
version = "0.1.0"
schema_version = 1
authors = ["Patrick Trickett"]
description = "Language support for the Gin programming language"
repository = "https://github.com/patrickett/gin"

[grammars.gin]
repository = "https://github.com/patrickett/gin"
rev = "2ab247a2d3b634763c4fbfa9e014dea3f104392b"
path = "editors/tree-sitter-gin"

[language_servers.ginlsp]
name = "Gin Language Server"
languages = ["Gin", "JSON"]
