[workspace]
default-members = [
    "crates/flask",
    "crates/ast",
    "crates/span",
    "crates/diagnostic",
    "crates/lexer",
    "crates/parser",
    "crates/typecheck",
    "crates/resolve",
    "crates/codegen",
    "crates/analysis",
    "editors/tree-sitter-gin",
    "tools/ginc",
    "tools/ginfmt",
    "tools/ginlsp",
]
members = [
    "editors/tree-sitter-gin",
    "crates/test-fixtures",
    "tools/begin",
    "crates/flask",
    "crates/ast",
    "crates/span",
    "crates/diagnostic",
    "crates/lexer",
    "crates/codegen",
    "crates/analysis",
    "crates/parser",
    "crates/resolve",
    "tools/ginc",
    "tools/ginfmt",
    "tools/ginlsp",
    "crates/typecheck",
    "crates/ast/signature",
    "crates/ast/format",
]
resolver = "3"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
correctness = "warn"
suspicious = "warn"
style = "warn"
complexity = "warn"
perf = "warn"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5.2", features = ["derive"] }
lsp-types = "0.94.1"
flask = { path = "crates/flask" }
ginc = { path = "tools/ginc" }
ast = { path = "crates/ast" }
ast-format = { path = "crates/ast/format" }
dashmap = "6.1.0"
span = { path = "crates/span" }
diagnostic = { path = "crates/diagnostic" }
lexer = { path = "crates/lexer" }
codegen = { path = "crates/codegen" }
analysis = { path = "crates/analysis" }
parser = { path = "crates/parser" }
ginfmt = { path = "tools/ginfmt" }
resolve = { path = "crates/resolve" }
test-fixtures = { path = "crates/test-fixtures" }
typecheck = { path = "crates/typecheck" }
indexmap = "2"
log = "0.4"
thiserror = "2.0.11"
crossbeam-channel = "0.5.15"
dirs = "6"
rayon = "1"
sha2 = "0.10"
ignore = "0.4"

strum = { version = "0.27", features = ["derive"] }
i256 = "0.2"
semver = "1"
criterion = "0.5"
