name = "Gin"
grammar = "gin"
path_suffixes = ["gin"]
line_comments = ["-- "]
block_comment = ["--- ", ""]
tab_size = 4
hard_tabs = false

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "'", end = "'", close = false, newline = false },
]
