[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
ast = { workspace = true }
flask = { workspace = true }
span = { workspace = true }
lexer = { workspace = true }
diagnostic = { workspace = true }
indexmap = { workspace = true }
internment = "0.8"
i256 = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
typecheck = { workspace = true }
criterion = "0.5"
test-fixtures = { workspace = true }

[[bench]]
name = "parser_bench"
harness = false
