//! Compile-time constant values and type constraint representations.

use internment::Intern;

/// The right-hand side of a comparison constraint.
#[derive(Debug, Clone, PartialEq)]
pub enum Bound {
    /// Compared to another variable, e.g. `i < len`.
    Variable(Intern<String>),
    /// Compared to a compile-time constant, e.g. `i < 10`.
    Constant(ConstValue),
}

/// Represents a narrowed type constraint on a variable.
#[derive(Debug, Clone, PartialEq)]
pub enum TypeConstraint {
    /// Variable is definitely a specific variant of a union.
    IsVariant(Intern<String>, Intern<String>),
    /// Variable is definitely NOT a specific variant.
    IsNotVariant(Intern<String>, Intern<String>),
    /// Variable satisfies a comparison constraint, e.g. `i < len`.
    ///
    /// Generated by while-loop conditions: inside the loop the condition holds,
    /// after the loop the negated condition holds.
    Compare { op: crate::BinOp, bound: Bound },
}

impl TypeConstraint {
    /// Returns true if this constraint contradicts another.
    pub fn contradicts(&self, other: &TypeConstraint) -> bool {
        match (self, other) {
            (TypeConstraint::IsVariant(u1, v1), TypeConstraint::IsVariant(u2, v2)) => {
                u1 == u2 && v1 != v2
            }
            (TypeConstraint::IsVariant(_, v1), TypeConstraint::IsNotVariant(_, v2)) => v1 == v2,
            (TypeConstraint::IsNotVariant(_, v1), TypeConstraint::IsVariant(_, v2)) => v1 == v2,
            _ => false,
        }
    }

    /// Negate this constraint (for after-loop / else-branch reasoning).
    ///
    /// `IsVariant(u, v)`    → `IsNotVariant(u, v)`
    /// `IsNotVariant(u, v)` → `IsVariant(u, v)`
    /// `Compare { op, bound }` → `Compare { op: op.negate(), bound }`
    pub fn negate(&self) -> Self {
        match self {
            TypeConstraint::IsVariant(u, v) => TypeConstraint::IsNotVariant(*u, *v),
            TypeConstraint::IsNotVariant(u, v) => TypeConstraint::IsVariant(*u, *v),
            TypeConstraint::Compare { op, bound } => TypeConstraint::Compare {
                op: op.negate(),
                bound: bound.clone(),
            },
        }
    }

    /// Format the constraint for hover display (just the constraint part, no variable name).
    ///
    /// E.g. `< len`, `>= 10`, `Some`, `None`.
    pub fn display_suffix(&self) -> String {
        match self {
            TypeConstraint::IsVariant(_, variant) => variant.as_str().to_string(),
            TypeConstraint::IsNotVariant(union, excluded) => {
                format!("not {}.{}", union.as_str(), excluded.as_str())
            }
            TypeConstraint::Compare { op, bound } => {
                let bound_str = match bound {
                    Bound::Variable(name) => name.as_str().to_string(),
                    Bound::Constant(val) => val.to_hover_string(),
                };
                format!("{} {}", op.symbol(), bound_str)
            }
        }
    }
}

/// A compile-time known constant value tracked through flow analysis.
#[derive(Debug, Clone, PartialEq)]
pub enum ConstValue {
    Int(i128),
    Float(f64),
    String(String),
    Tag {
        name: Intern<String>,
        /// Fully qualified path (e.g., `Bool.False`), if known.
        qual_path: Option<String>,
        args: Vec<ConstValue>,
    },
    /// A record/struct value with named fields, e.g. `Register(value: 'x0')`.
    Record {
        fields: Vec<(Intern<String>, ConstValue)>,
    },
    /// A list literal value, e.g. `[Output[X0], Input[X16]]`.
    List(Vec<ConstValue>),
}

impl ConstValue {
    /// Try to evaluate a binary operation on two constant values.
    /// Returns `None` if the operation cannot be constant-folded.
    pub fn eval_binop(&self, op: &crate::BinOp, rhs: &ConstValue) -> Option<ConstValue> {
        use crate::BinOp;
        match (self, rhs) {
            (ConstValue::Int(a), ConstValue::Int(b)) => match op {
                BinOp::Add => Some(ConstValue::Int(a.wrapping_add(*b))),
                BinOp::Subtract => Some(ConstValue::Int(a.wrapping_sub(*b))),
                BinOp::Multiply => Some(ConstValue::Int(a.wrapping_mul(*b))),
                BinOp::Divide => {
                    if *b != 0 {
                        Some(ConstValue::Int(a / *b))
                    } else {
                        None
                    }
                }
                BinOp::Modulo => {
                    if *b != 0 {
                        Some(ConstValue::Int(a % *b))
                    } else {
                        None
                    }
                }
                _ => None,
            },
            (ConstValue::Float(a), ConstValue::Float(b)) => match op {
                BinOp::Add => Some(ConstValue::Float(a + b)),
                BinOp::Subtract => Some(ConstValue::Float(a - b)),
                BinOp::Multiply => Some(ConstValue::Float(a * b)),
                BinOp::Divide => Some(ConstValue::Float(a / b)),
                _ => None,
            },
            _ => None,
        }
    }

    /// Format this value for hover display (without the variable name).
    pub fn to_hover_string(&self) -> String {
        match self {
            ConstValue::Int(i) => i.to_string(),
            ConstValue::Float(f) => f.to_string(),
            ConstValue::String(s) => format!("\"{s}\""),
            ConstValue::Tag {
                name,
                qual_path,
                args,
            } => {
                let display_name = qual_path.as_deref().unwrap_or_else(|| name.as_str());
                if args.is_empty() {
                    display_name.to_string()
                } else {
                    let parts: Vec<String> = args.iter().map(|a| a.to_hover_string()).collect();
                    format!("{}({})", display_name, parts.join(", "))
                }
            }
            ConstValue::Record { fields } => {
                let parts: Vec<String> = fields
                    .iter()
                    .map(|(n, v)| format!("{}: {}", n.as_str(), v.to_hover_string()))
                    .collect();
                format!("{{ {} }}", parts.join(", "))
            }
            ConstValue::List(items) => {
                let parts: Vec<String> = items.iter().map(|v| v.to_hover_string()).collect();
                format!("[{}]", parts.join(", "))
            }
        }
    }

    /// Return a display name for this constant value, used as the variant name
    /// in the variant map for pattern matching.
    pub fn display_name(&self) -> Intern<String> {
        match self {
            ConstValue::String(s) => Intern::new(s.clone()),
            ConstValue::Int(i) => Intern::new(i.to_string()),
            ConstValue::Float(f) => Intern::new(f.to_string()),
            ConstValue::Tag { name, .. } => *name,
            ConstValue::Record { .. } => Intern::new(String::from("Record")),
            ConstValue::List(_) => Intern::new(String::from("List")),
        }
    }

    /// Get a field value from a Record constant by name.
    pub fn get_field(&self, name: &str) -> Option<&ConstValue> {
        match self {
            ConstValue::Record { fields } => fields
                .iter()
                .find(|(k, _)| k.as_str() == name)
                .map(|(_, v)| v),
            _ => None,
        }
    }

    /// Get the string value if this is a String constant.
    pub fn as_str(&self) -> Option<&str> {
        match self {
            ConstValue::String(s) => Some(s.as_str()),
            _ => None,
        }
    }

    /// Get the list items if this is a List constant.
    pub fn as_list(&self) -> Option<&[ConstValue]> {
        match self {
            ConstValue::List(items) => Some(items.as_slice()),
            _ => None,
        }
    }

    /// Find the index of a literal value within a set of `ConstValue` discriminants.
    /// Used for compiling ConstUnion construction.
    pub fn find_discriminant(lit: &crate::Literal, values: &[ConstValue]) -> Option<usize> {
        match lit {
            crate::Literal::String(s) => values
                .iter()
                .position(|v| matches!(v, ConstValue::String(vs) if vs == s)),
            crate::Literal::Int(n) => values
                .iter()
                .position(|v| matches!(v, ConstValue::Int(vn) if *vn == *n as i128)),
            crate::Literal::Float(f) => values
                .iter()
                .position(|v| matches!(v, ConstValue::Float(vf) if vf.to_bits() == f.to_bits())),
            crate::Literal::Number(n) => values
                .iter()
                .position(|v| matches!(v, ConstValue::Int(vn) if *vn == *n as i128)),
        }
    }
}
