[package]
name = "codegen"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
ast = { workspace = true }

typecheck = { workspace = true }
parser = { workspace = true }
diagnostic = { workspace = true }
span = { workspace = true }
i256 = { workspace = true }
melior = "0.27"
mlir-sys = "220.0.2"
internment = "0.8"
strum = { workspace = true }
thiserror = { workspace = true }
flask = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
parser = { workspace = true }

[[bench]]
name = "codegen_bench"
harness = false
